**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

In [1]:
import numpy as np

In Python, there is a difference between the data types of lists and arrays.

A list is a built-in data type in Python that represents a collection of ordered elements that can be of any data type. Lists are dynamic, which means their size can be changed during runtime.

On the other hand, arrays in Python are not built-in data types, but can be created using third-party libraries such as NumPy. NumPy arrays are similar to lists in that they represent a collection of ordered elements. However, unlike lists, NumPy arrays have a fixed size and all the elements in the array must be of the same data type.

In summary, in Python, a list is a built-in data type that can contain elements of different data types, while an array created using NumPy is a third-party data type that has a fixed size and all elements must be of the same data type.

In [3]:
lists = [1,2,3,4]
lists2 = np.array([1,2,3,4,5])
print(type(lists))
print(type(lists2))

<class 'list'>
<class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [6]:
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:**

In [10]:
array_list = np.array(object = list_, dtype = int)

In Python, there is a difference between the data types of lists and arrays.

A list is a built-in data type in Python that represents a collection of ordered elements that can be of any data type. Lists are dynamic, which means their size can be changed during runtime.

On the other hand, arrays in Python are not built-in data types, but can be created using third-party libraries such as NumPy. NumPy arrays are similar to lists in that they represent a collection of ordered elements. However, unlike lists, NumPy arrays have a fixed size and all the elements in the array must be of the same data type.

In summary, in Python, a list is a built-in data type that can contain elements of different data types, while an array created using NumPy is a third-party data type that has a fixed size and all elements must be of the same data type.

In [11]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size**

In [13]:
import numpy as np

# create a sample NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# find the shape of the array
array_shape = num_array.shape

# find the size of the array
array_size = num_array.size

# print the shape and size of the array
print("Array shape: ", array_shape)
print("Array size: ", array_size)


Array shape:  (3, 3)
Array size:  9


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [18]:
arrays = np.array((np.zeros(3),np.zeros(3),np.zeros(3)))

In [19]:
arrays.shape

(3, 3)

In [20]:
arrays.size

9

**Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [23]:
import numpy as np

# create identity matrix using numpy
identity_matrix = np.identity(5)

# print the identity matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
